---
# Install Apache on Client1
- hosts: Client1
  become: true
  become_user: root
  tasks:
    - name: update_cache
      apt:
        update_cache: yes
    - name: Install apache
      apt:
        name: apache2
        state: latest