---
# tasks file for apache
- name: update_cache
  apt:
    update_cache: yes
- name: Install apache
  apt:
    name: apache2
    state: latest
- name: Copy index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html
  notify: restart apache
- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present
- name: Display message 
  debug:
    msg: "Installed Apache  and Java Successfully"