---
- hosts: QA
  become: true
  tasks:
    - name: Update apt package manager repositories cache
      apt:
        update_cache: yes
    - name: Install Java using Ansible
      apt:
        name: openjdk-11-jdk
        state: present
- hosts: Client2
  become: true
  tasks:
    - name: Update the software package repository
      apt:
        update_cache: yes
    - name: Install MySQL
      apt:
        name:
          - mysql-server
          - mysql-client
        state: latest
 
       
